---
- name: Install and configure Prometheus monitoring on the cluster
  hosts: prometheus
  become: yes # run with elevated privileges
  gather_facts: no
  any_errors_fatal: true

  vars:
    template_dir: ../conf/monitoring/hadoop
    prometheus_target_tmpl: ../conf/metrics/targets
    prometheus_home: '{{ deploy_dir }}/prometheus'
    prometheus_target_dir: '{{ prometheus_home }}/targets'
    prometheus_data_loc: '{{ data_dir }}/prometheus'
    systemd_template_dir: ../systemd-template/monitoring
    systemd_service_dir: /etc/systemd/system

    namenode_metrics_port: 7021
    datanode_metrics_port: 7022
    journalnode_metrics_port: 7023
    resourcemanager_metrics_port: 7024
    nodemanager_metrics_port: 7025
    historyserver_metrics_port: 7026

    hmaster_metrics_port: 7027
    regionserver_metrics_port: 7028

    services:
      - { name: prometheus.service, group: prometheus }

  tasks:

    - name: test connectivity
      ping:

    - name: ensure prometheus target directory
      file:
        path: '{{ prometheus_target_dir }}'
        state: directory

    - name: ensure prometheus data directory
      become: true
      file:
        path: '{{ prometheus_data_loc }}'
        owner: '{{ ansible_user }}'
        group: '{{ ansible_user }}'
        state: directory

    - name: generate target config to "{{ prometheus_target_dir }}"
      template:
        src: '{{ prometheus_target_tmpl }}/{{ item }}'
        dest: '{{ prometheus_target_dir }}/{{ item }}'
      with_items:
        - hadoop-cluster.yaml
        - hbase-cluster.yaml
        - zk-cluster.yaml
        - prometheus-servers.yaml

    - name: Remove the existing 'prometheus.yml' on the remote machine
      file:
        path: "{{ prometheus_home }}/prometheus.yml"
        state: absent

    - name: Sync prometheus config
      template:
        src: '{{ template_dir }}/{{ item }}'
        dest: '{{ prometheus_home }}/{{ item }}'
      with_items:
        - prometheus.yaml

    - name: Sync systemd config for services
      become: true
      template:
        src: "{{ systemd_template_dir }}/{{ item.name }}"
        dest: "{{ systemd_service_dir }}/{{ item.name }}"
      loop: "{{ services }}"

    - name: Import systemd restart tasks
      include_tasks: restart_systemd_service.yaml
      loop: "{{ services }}"
      loop_control:
        loop_var: item
