---
- name: Hadoop Cluster Deployment
  hosts: hadoop_nodes
  gather_facts: no
  any_errors_fatal: true

  vars:
    hadoop_home: '{{ deploy_dir }}/hadoop'
    hadoop_conf_dir: '{{ hadoop_home }}/etc/hadoop'
    hadoop_data_dir: '{{ data_dir }}/hadoop'

  tasks:
    - name: Verify QuorumPeerMain process exist on each zk_node
      shell: ". /etc/profile && jps | grep QuorumPeerMain"
      register: quorum_check
      failed_when: quorum_check.stdout == ""
      delegate_to: "{{ item }}"
      with_items: "{{ groups['zk_nodes'] }}"

    - name: Get ZooKeeper version and status
      shell: ". /etc/profile && /opt/zookeeper/bin/zkServer.sh version && /opt/zookeeper/bin/zkServer.sh status"
      delegate_to: "{{ item }}"
      with_items: "{{ groups['zk_nodes'] }}"

    - name: Start all journalnodes
      shell: ". /etc/profile && nohup hdfs --daemon start journalnode"
      delegate_to: "{{ item }}"
      with_items: "{{ groups['journalnodes'] }}"

    - name: Check JournalNode process exist on all nodes in journalnodes group
      shell: ". /etc/profile && jps | grep JournalNode"
      register: journalnode_check
      failed_when: journalnode_check.stdout == ""
      delegate_to: "{{ item }}"
      with_items: "{{ groups['journalnodes'] }}"

    - name: Format namenode on the first node within namenodes group
      shell: ". /etc/profile && hdfs namenode -format"
      delegate_to: "{{ groups['namenodes'][0] }}"

    - name: Start the first namenode in the namenodes group
      shell: ". /etc/profile && nohup hdfs --daemon start namenode"
      delegate_to: "{{ groups['namenodes'][0] }}"

    - name: Check NameNode process exist on the first namenode in the namenodes group
      shell: ". /etc/profile && jps | grep NameNode"
      register: namenode_check
      failed_when: namenode_check.stdout == ""
      delegate_to: "{{ groups['namenodes'][0] }}"

    - name: Bootstrap standby namenode on remaining namenodes
      shell: ". /etc/profile && hdfs namenode -bootstrapStandby"
      delegate_to: "{{ item }}"
      with_items: "{{ groups['namenodes'][1:] }}"

    - name: Start namenode on remaining namenodes
      shell: ". /etc/profile && nohup hdfs --daemon start namenode"
      delegate_to: "{{ item }}"
      with_items: "{{ groups['namenodes'][1:] }}"

    - name: Check NameNode process on remaining namenodes
      shell: ". /etc/profile && jps | grep NameNode"
      register: namenode_check
      failed_when: namenode_check.stdout == ""
      delegate_to: "{{ item }}"
      with_items: "{{ groups['namenodes'][1:] }}"

    - name: Start datanode on datanodes
      shell: ". /etc/profile && nohup hdfs --daemon start datanode"
      delegate_to: "{{ item }}"
      with_items: "{{ groups['datanodes'] }}"

    - name: Check DataNode process on datanodes
      shell: ". /etc/profile && jps | grep DataNode"
      register: datanode_check
      failed_when: datanode_check.stdout == ""
      delegate_to: "{{ item }}"
      with_items: "{{ groups['datanodes'] }}"

    - name: Check standby state of namenodes
      shell: ". /etc/profile && hdfs haadmin -getServiceState nn1 && hdfs haadmin -getServiceState nn2"
      delegate_to: "{{ groups['namenodes'][0] }}"

    - name: Format ZooKeeper Failover Controller
      shell: ". /etc/profile && hdfs zkfc -formatZK"
      delegate_to: "{{ groups['namenodes'][0] }}"

    - name: Stop HDFS
      shell: ". /etc/profile && stop-dfs.sh"
      delegate_to: "{{ groups['namenodes'][0] }}"

    - name: Start HDFS
      shell: ". /etc/profile && start-dfs.sh"
      delegate_to: "{{ groups['namenodes'][0] }}"

    - name: Check DFSZKFailoverController process on namenodes
      shell: ". /etc/profile && jps | grep FailoverController"
      register: zk_controller_check
      failed_when: zk_controller_check.stdout == ""
      delegate_to: "{{ item }}"
      with_items: "{{ groups['namenodes'] }}"

    - name: Gather state of each NameNode
      shell: ". /etc/profile && hdfs haadmin -getServiceState {{ hostvars[item]['id'] }}"
      register: namenode_states
      delegate_to: "{{ item }}"
      with_items: "{{ groups['namenodes'] }}"

    - name: Check that only one NameNode is active and first is active
      assert:
        that:
          - namenode_states.results | selectattr('stdout', 'equalto', 'active') | list | count == 1
          - namenode_states.results | selectattr('item', 'equalto', groups['namenodes'][0]) | map(attribute='stdout') | first == 'active'
        fail_msg: "Assertion failed: There should be exactly one active NameNode and the first NameNode should be active"
        success_msg: "One active NameNode verified and first NameNode is active"

    - name: Start YARN
      shell: ". /etc/profile && start-yarn.sh"
      delegate_to: "{{ groups['namenodes'][0] }}"

    - name: Check ResourceManager process on ResourceManager nodes
      shell: ". /etc/profile && jps | grep ResourceManager"
      register: resourcemanager_check
      failed_when: resourcemanager_check.stdout == ""
      delegate_to: "{{ item }}"
      with_items: "{{ groups['resourcemanagers'] }}"

    - name: Check NodeManager process on Hadoop nodes
      shell: ". /etc/profile && jps | grep NodeManager"
      register: nodemanager_check
      failed_when: nodemanager_check.stdout == ""
      delegate_to: "{{ item }}"
      with_items: "{{ groups['hadoop_nodes'] }}"

    - name: Check YARN ResourceManager service state on each node
      shell: ". /etc/profile && yarn rmadmin -getServiceState {{ item }}"
      register: rm_service_state
      delegate_to: "{{ item }}"
      with_items: "{{ groups['resource_managers'] }}"
      ignore_errors: true

    - name: Count active ResourceManagers
      set_fact:
        active_rms: "{{ rm_service_state.results | selectattr('stdout', 'equalto', 'active') | list | count }}"

    - name: Assert only one active ResourceManager
      assert:
        that:
          - active_rms == 1
        fail_msg: "There is not exactly one active ResourceManager. Active ResourceManager count: {{ active_rms }}"
        success_msg: "Exactly one active ResourceManager found."

  # Add a rescue block to clean up in case of any failure
  rescue:
    - name: Stop YARN services on NameNodes
      shell: ". /etc/profile && stop-yarn.sh"
      delegate_to: "{{ groups['namenodes'][0] }}"
      ignore_errors: yes

    - name: Stop HDFS services on NameNodes
      shell: ". /etc/profile && stop-dfs.sh"
      delegate_to: "{{ groups['namenodes'][0] }}"
      ignore_errors: yes

    - name: Stop JournalNode processes
      shell: ". /etc/profile && nohup hdfs --daemon stop journalnode"
      delegate_to: "{{ groups['journalnodes'] }}"
      ignore_errors: yes

    - name: Clean up Hadoop data files
      find:
        paths: "{{ hadoop_data_dir }}"
        file_type: file
      register: data_files
    - name: Remove Hadoop data files
      file:
        path: "{{ item.path }}"
        state: absent
      with_items: "{{ data_files.files }}"
