---
- name: Install Hadoop Package
  hosts: ozone_newborn
  gather_facts: false
  any_errors_fatal: true

  vars:
    install_from_remote: false
    local_repo: '../repo/ozone'
    remote_repo: '~/repo/ozone'
    # NOTE: Change the `src` below to correct package in `local_repo` if install via local package.
    package_info:
      - { src: 'openlogic-openjdk-8u392-b08-linux-x64.tar.gz', dst: 'java/jdk8u392-b08', home: 'jdk8', link: 'https://builds.openlogic.com/downloadJDK/openlogic-openjdk/8u392-b08/openlogic-openjdk-8u392-b08-linux-x64.tar.gz' }
      - { src: 'ozone-1.3.0.tar.gz', dst: 'apache/ozone-1.3.0', home: 'ozone', link: 'https://archive.apache.org/dist/ozone/1.3.0/ozone-1.3.0.tar.gz' }

  tasks:

    - name: test connectivity
      ping:

    - name: copy or download ozone package
      block:
        - name: copy package from local repo
          copy:
            src: '{{ local_repo }}'
            dest: '~/repo'
          when: not install_from_remote

        - name: Copy the download script to the remote machine
          copy:
            src: '{{ local_repo }}/download_util.sh'
            dest: /tmp/download_util.sh
            mode: '0755'
          when: install_from_remote

        - name: Download packages using the custom script
          command: /tmp/download_util.sh "{{ item.link }}" "{{ remote_repo }}"
          with_items: "{{ package_info }}"
          when: install_from_remote

    - name: prepare directory
      become: true
      file:
        state: directory
        path: '{{ deploy_dir }}/{{ item.dst }}'
        owner: '{{ ansible_user }}'
        group: '{{ ansible_user }}'
        mode: 0775
        recurse: yes
      with_items: '{{ package_info }}'

    - name: create link
      become: true
      file:
        state: link
        src: '{{ deploy_dir }}/{{ item.dst }}'
        dest: '{{ deploy_dir }}/{{ item.home }}'
        owner: '{{ ansible_user }}'
        group: '{{ ansible_user }}'
      with_items: '{{ package_info }}'

    - name: install package
      unarchive:
        src: '{{ remote_repo }}/{{ item.src }}'
        dest: '{{ deploy_dir }}/{{ item.dst }}'
        remote_src: yes
        extra_opts:
          - --strip-components=1
      with_items: '{{ package_info }}'

    - name: config /etc/profile
      become: true
      blockinfile:
        dest: '/etc/profile'
        marker: "# {mark} ANSIBLE MANAGED PROFILE"
        block: |
          export JAVA_HOME={{ deploy_dir }}/jdk8
          export OZONE_HOME={{ deploy_dir }}/ozone
          export PATH=$JAVA_HOME/bin:$OZONE_HOME/bin:$OZONE_HOME/sbin:$PATH

    - name: config ozone-env.sh
      blockinfile:
        dest: '{{ deploy_dir }}/ozone/etc/hadoop/ozone-env.sh'
        marker: "# {mark} ANSIBLE MANAGED DEFAULT OZONE ENV"
        block: |
          export JAVA_HOME={{ deploy_dir }}/jdk8
          export OZONE_HOME={{ deploy_dir }}/ozone
          export OZONE_LOG_DIR={{ data_dir }}/ozone/logs

    - name: Create log directory
      become: true
      file:
        state: directory
        path: '{{ data_dir }}/ozone/logs'
        owner: '{{ ansible_user }}'
        group: '{{ ansible_user }}'
        mode: 0775
        recurse: yes