---
- name: Install Hadoop Package
  hosts: newborn
  gather_facts: no
  any_errors_fatal: true

  vars:
    install_from_remote: true
    local_repo: '../repo/hadoop'
    remote_repo: '~/repo/hadoop'
    # NOTE: Change the `src` below to correct package in `local_repo` if install via local package.
    package_info:
      - {src: 'openlogic-openjdk-17.0.9+9-linux-x64.tar.gz', dst: 'java/jdk-17.0.9+9', home: 'jdk17', link: 'https://builds.openlogic.com/downloadJDK/openlogic-openjdk/17.0.9+9/openlogic-openjdk-17.0.9+9-linux-x64.tar.gz'}
      - {src: 'openlogic-openjdk-8u392-b08-linux-x64.tar.gz', dst: 'java/jdk8u392-b08', home: 'jdk8', link: 'https://builds.openlogic.com/downloadJDK/openlogic-openjdk/8u392-b08/openlogic-openjdk-8u392-b08-linux-x64.tar.gz'}
      - {src: 'apache-zookeeper-3.8.3-bin.tar.gz', dst: 'apache/zookeeper-3.8.3', home: 'zookeeper', link: 'https://archive.apache.org/dist/zookeeper/zookeeper-3.8.3/apache-zookeeper-3.8.3-bin.tar.gz'}
      - {src: 'hbase-2.4.17-bin.tar.gz', dst: 'apache/hbase-2.4.17',home: 'hbase', link: 'https://archive.apache.org/dist/hbase/2.4.17/hbase-2.4.17-bin.tar.gz'}
      - {src: 'hadoop-3.3.6.tar.gz', dst: 'apache/hadoop-3.3.6', home: 'hadoop', link: 'https://archive.apache.org/dist/hadoop/core/hadoop-3.3.6/hadoop-3.3.6.tar.gz'}

  tasks:

    - name: test connectivity
      ping:

    - name: copy or download hadoop package
      block:
        - name: copy package from local repo
          copy:
            src: '{{ local_repo }}'
            dest: '~/repo'
          when: not install_from_remote

        - name: download package from remote repo
          get_url:
            url: "{{ item.link }}"
            dest: "~/repo"
          with_items: "{{ package_info }}"
          when: install_from_remote

    - name: prepare directory
      become: true # become root
      file:
        state: directory
        path: '{{ deploy_dir }}/{{ item.dst }}'
        owner: '{{ ansible_user }}'
        group: '{{ ansible_user }}'
        mode: 0775
        recurse: yes
      with_items: '{{ package_info }}'

    - name: create link
      become: true # become root
      file:
        state: link
        src: '{{ deploy_dir }}/{{ item.dst }}'
        dest: '{{ deploy_dir }}/{{ item.home }}'
        owner: '{{ ansible_user }}'
        group: '{{ ansible_user }}'
      with_items: '{{ package_info }}'

    - name: install package
      unarchive:
        src: '{{ remote_repo }}/{{ item.src }}'
        dest: '{{ deploy_dir }}/{{ item.dst }}'
        remote_src: yes
        extra_opts:
          - --strip-components=1
      with_items: '{{ package_info }}'

    - name: config /etc/profile
      become: true
      blockinfile:
        dest: '/etc/profile'
        marker: "# {mark} ANSIBLE MANAGED PROFILE"
        block: |
          export JAVA_HOME={{ deploy_dir }}/jdk8
          export HADOOP_HOME={{ deploy_dir }}/hadoop
          export HBASE_HOME={{ deploy_dir }}/hbase
          export PATH=$JAVA_HOME/bin:$HADOOP_HOME/bin:$HADOOP_HOME/sbin:$HBASE_HOME/bin:$PATH

    - name: config zkEnv.sh
      lineinfile:
        path: '{{ deploy_dir }}/zookeeper/bin/zkEnv.sh'
        line: 'JAVA_HOME={{ deploy_dir }}/jdk17'
        insertafter: '^#\!\/usr\/bin'
        firstmatch: yes

    - name: config hadoop-env.sh
      blockinfile:
        dest: '{{ deploy_dir }}/hadoop/etc/hadoop/hadoop-env.sh'
        marker: "# {mark} ANSIBLE MANAGED DEFAULT HADOOP ENV"
        block: |
          export JAVA_HOME={{ deploy_dir }}/jdk8

    - name: config hbase-env.sh
      blockinfile:
        dest: '{{ deploy_dir }}/hbase/conf/hbase-env.sh'
        marker: "# {mark} ANSIBLE MANAGED DEFAULT HBASE ENV"
        block: |
          export JAVA_HOME={{ deploy_dir }}/jdk17
          export HBASE_MANAGES_ZK=false
          export HBASE_LIBRARY_PATH={{ deploy_dir }}/hadoop/lib/native
          export HBASE_OPTS="$HBASE_OPTS --add-exports=java.base/jdk.internal.access=ALL-UNNAMED --add-exports=java.base/jdk.internal=ALL-UNNAMED --add-exports=java.base/jdk.internal.misc=ALL-UNNAMED --add-exports=java.base/sun.security.pkcs=ALL-UNNAMED --add-exports=java.base/sun.nio.ch=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.lang.reflect=ALL-UNNAMED --add-opens java.base/java.io=ALL-UNNAMED --add-opens java.base/java.nio=ALL-UNNAMED --add-opens java.base/jdk.internal=ALL-UNNAMED --add-opens java.base/jdk.internal.misc=ALL-UNNAMED --add-opens java.base/jdk.internal.access=ALL-UNNAMED"

#    - name: patch hbase
#      copy:
#        src: '{{ local_repo }}/hbase-server-2.4.17.jar'
#        dest: '{{ deploy_dir }}/hbase/lib'
#        backup: no
#        force: yes

    - name: link hadoop config
      file:
        state: link
        src: '{{ deploy_dir }}/hadoop/etc/hadoop/{{ item }}'
        dest: '{{ deploy_dir }}/hbase/conf/{{ item }}'
      with_items:
        - core-site.xml
        - hdfs-site.xml

    - name: Install EPEL Repository (CentOS)
      yum:
        name: epel-release
        state: present
      when: ansible_facts['distribution'] == "CentOS"

    - name: Update yum cache (CentOS)
      yum:
        name: '*'
        state: latest
      when: ansible_facts['distribution'] == "CentOS"

    - name: Install libraries (CentOS)
      yum:
        name:
          - snappy
          - snappy-devel
          - lz4
          - lz4-devel
          - libzstd
          - libzstd-devel
        state: present
      when: ansible_facts['distribution'] == "CentOS"

    - name: Update apt cache (Ubuntu)
      apt:
        update_cache: yes
      when: ansible_facts['distribution'] == "Ubuntu"

    - name: Install libraries (Ubuntu)
      apt:
        name:
          - libsnappy1v5
          - libsnappy-dev
          - liblz4-1
          - liblz4-dev
          - libzstd1
          - libzstd-dev
        state: present
      when: ansible_facts['distribution'] == "Ubuntu"

    - name: check hadoop native
      shell: '{{ deploy_dir }}/hadoop/bin/hadoop checknative -a'
      register: hadoop_checknative
      failed_when: false
      changed_when: false
      ignore_errors: yes
      environment:
        JAVA_HOME: '{{ deploy_dir }}/jdk8'

    - name: hadoop native status
      debug:
        msg: "{{ hadoop_checknative.stdout_lines }}"

    - name: check hbase native
      shell: '{{ deploy_dir }}/hbase/bin/hbase --config ~/conf_hbase org.apache.hadoop.util.NativeLibraryChecker'
      register: hbase_checknative
      failed_when: false
      changed_when: false
      ignore_errors: yes
      environment:
        JAVA_HOME: '{{ deploy_dir }}/jdk17'
        HBASE_LIBRARY_PATH: '{{ deploy_dir }}/hadoop/lib/native'

    - name: hbase native status
      debug:
        msg: "{{ hbase_checknative.stdout_lines|select('match', '^[^0-9]') | list }}"

    - name: test native compresssion
      shell: '{{ deploy_dir }}/hbase/bin/hbase org.apache.hadoop.hbase.util.CompressionTest file:///tmp/test {{ item }}'
      register: 'compression'
      failed_when: false
      changed_when: false
      ignore_errors: yes
      environment:
        JAVA_HOME: '{{ deploy_dir }}/jdk17'
        HBASE_LIBRARY_PATH: '{{ deploy_dir }}/hadoop/lib/native'
      with_items:
        - snappy
        - lz4

    - name: native compresssion status
      vars:
        results: "{{ compression | json_query('results[*].{type:item, result:stdout}') }}"
      debug:
        msg: |
          {% for r in results %} {{ r.type }} => {{ r.result == 'SUCCESS' }} {% endfor %}
