---
- name: Provision Ozone Cluster
  hosts: ozone_nodes
  gather_facts: no
  any_errors_fatal: true

  vars:
    ozone_data_dir: '{{ data_dir }}/ozone/data'
    ozone_metadata_dir: '{{ ozone_data_dir }}/metadata'
    systemd_template_dir: ../systemd-template/ozone
    systemd_service_dir: /etc/systemd/system
    services:
      - { name: om.service, group: oms }
      - { name: scm.service, group: scms }
      - { name: datanode.service, group: ozone_nodes }
      - { name: recon.service, group: recon }
      - { name: s3g.service, group: s3g }

  tasks:

    - name: Determine the first ozone manager host in the oms group
      set_fact:
        first_om_node: "{{ groups['oms'][0] }}"
    - name: Determine the first ozone storage container manager host in the scms group
      set_fact:
        first_scm_node: "{{ groups['scms'][0] }}"

    - name: Check if the first scm is initialized
      stat:
        path: "{{ozone_metadata_dir}}/scm/current/VERSION"
      register: scm_init_check

    - name: init first scm if not initialized
      shell: ". /etc/profile && nohup ozone scm --init"
      when:
        - inventory_hostname == first_scm_node
        - not scm_init_check.stat.exists

    - name: start first scm
      shell: ". /etc/profile && nohup ozone --daemon start scm"
      when: inventory_hostname == first_scm_node

    - name: Set a variable for the length of the 'scms' group
      set_fact:
        scms_length: "{{ groups['scms'] | length }}"

    - name: Sequentially bootstrap other SCMs
      include_tasks: bootstrap-scm.yaml
      loop: "{{ range(1, scms_length|int) }}"
      loop_control:
        index_var: item
      when: scms_length|int >= 2

    - name: Wait for the SCM "{{ groups['scms'][-1] }}" ratis port to become available
      wait_for:
        host: "{{ groups['scms'][-1] }}"
        port: 9894
        timeout: 90
      when:
        - inventory_hostname == groups['scms'][-1]
        - scms_length|int >= 2

    - name: Check StorageContainerManagerStarter process exist on the scms group
      shell: ". /etc/profile && jps | grep StorageContainerManagerStarter"
      register: scm_check
      failed_when: scm_check.stdout == ""
      when:
        - inventory_hostname in groups['scms']

    - name: Check if the om has already initialized
      stat:
        path: "{{ozone_metadata_dir}}/om/current/VERSION"
      register: om_init_check

    - name: init oms
      shell: ". /etc/profile && nohup ozone om --init"
      when:
        - inventory_hostname in groups['oms']
        - not om_init_check.stat.exists

    - name: Sync systemd config for services
      become: true
      template:
        src: "{{ systemd_template_dir }}/{{ item.name }}"
        dest: "{{ systemd_service_dir }}/{{ item.name }}"
      loop: "{{ services }}"
      when: inventory_hostname in groups[item.group]

    - name: Import systemd restart tasks
      include_tasks: restart_systemd_service.yaml
      loop: "{{ services }}"
      when: inventory_hostname in groups[item.group]
      loop_control:
        loop_var: item
