---
- name: Shutdown Hadoop Cluster
  hosts: all
  gather_facts: no

  vars:
    zk_home: '{{ deploy_dir }}/zookeeper'

  tasks:
    - name: Check running processes before shutdown
      shell: ". /etc/profile && jps"
      register: before_shutdown
      changed_when: false

    - name: Stop YARN services on NameNodes
      shell: ". /etc/profile && stop-yarn.sh"
      delegate_to: "{{ groups['namenodes'][0] }}"

    - name: Stop HDFS services on NameNodes
      shell: ". /etc/profile && stop-dfs.sh"
      delegate_to: "{{ groups['namenodes'][0] }}"

    - name: Stop JournalNode processes
      shell: ". /etc/profile && nohup hdfs --daemon stop journalnode"
      delegate_to: "{{ groups['journalnodes'] }}"
      ignore_errors: yes

    - name: Stop ZooKeeper services on ZooKeeper nodes
      shell: ". /etc/profile && {{ zk_home }}/bin/zkServer.sh stop"
      delegate_to: "{{ groups['zk_nodes'] }}"
      ignore_errors: yes

    - name: Check running processes after shutdown
      shell: ". /etc/profile && jps"
      register: after_shutdown
      changed_when: false

    - name: Display processes before shutdown
      debug:
        msg: "{{ before_shutdown.stdout_lines }}"

    - name: Display processes after shutdown
      debug:
        msg: "{{ after_shutdown.stdout_lines }}"